### ISSUE TITLE
What does this plugin do that I can't do with the "toggle blockquote" built-in command?!

### ISSUE THREAD

**Issue by YousufSSyed** [Cleoche/obsidian-callout-integrator#6]
I tried out Callout Integrator and while it does add text into callouts like its supposed to, I don't see the point in using it. If text is not inside a callout, I can just select it use the `Toggle Blockquote` command, then remove blank lines between the text and the callout.

**Comment by Cleoche** [comment]
The difference here is that this plugin works to allow the user to use nested callouts. With a "toggle" mechanism, you can only go "off" or "on", rather than multiple layers. If you have any suggestions for how to improve usability or make the purpose of the plugin more clear, I'm open to suggestions.

**Comment by YousufSSyed** [comment]
@Cleoche I looked at this plugin again and I think you should specify it in the readme
